# Generated by Django 3.0.8 on 2020-08-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='df_goods',
        ),
        migrations.AlterModelTable(
            name='goodsimage',
            table='df_goods_image',
        ),
        migrations.AlterModelTable(
            name='goodssku',
            table='df_goods_sku',
        ),
        migrations.AlterModelTable(
            name='goodstype',
            table='df_goods_type',
        ),
        migrations.AlterModelTable(
            name='indexgoodsbanner',
            table='df_index_banner',
        ),
        migrations.AlterModelTable(
            name='indexpromotionbanner',
            table='df_index_promotion',
        ),
        migrations.AlterModelTable(
            name='indextypegoodsbanner',
            table='df_index_type_goods',
        ),
    ]
