# Generated by Django 3.0.8 on 2020-08-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='df_address',
        ),
        migrations.AlterModelTable(
            name='user',
            table='df_user',
        ),
    ]
