# Generated by Django 3.0.8 on 2020-08-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200812_2209'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordergoods',
            table='df_order_goods',
        ),
        migrations.AlterModelTable(
            name='orderinfo',
            table='df_order_info',
        ),
    ]
